"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](dim_blue)\
$os\
$username\
[](bg:orange fg:dim_blue)\
$directory\
[](fg:orange bg:green)\
$git_branch\
$git_status\
[](fg:green bg:cyan)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:cyan bg:blue)\
$docker_context\
[](fg:blue bg:magenta)\
$time\
[ ](fg:magenta)\
$line_break$character"""

palette = 'dracula_pro'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[palettes.dracula_pro]
black = '#22212c'
red = '#ff9580'
green = '#8aff80'
yellow = '#ffff80'
blue = '#9580ff'
magenta = '#ff80bf'
cyan = '#80ffea'
white = '#f8f8f2'
bright_black = '#504c67'
bright_red = '#ffaa99'
bright_green = '#a2ff99'
bright_yellow = '#ffff99'
bright_blue = '#aa99ff'
bright_magenta = '#ff99cc'
bright_cyan = '#99ffee'
bright_white = '#ffffff'
dim_black = '#1b1a23'
dim_red = '#cc7766'
dim_green = '#6ecc66'
dim_yellow = '#cccc66'
dim_blue = '#7766cc'
dim_magenta = '#cc6699'
dim_cyan = '#66ccbb'
dim_white = '#c6c6c2'
background = '#22212c'
foreground = '#f8f8f2'
comment = '#7970a9'
selection = '#454158'
cursor = '#7970a9'
orange = '#ffca80'

[os]
disabled = false
style = "bg:dim_blue fg:bright_white"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = ""
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:dim_blue fg:bright_white"
style_root = "bg:dim_blue fg:bright_white"
format = '[ $user ]($style)'

[directory]
style = "fg:black bg:orange"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:cyan"
format = '[[ $symbol $branch ](fg:dim_black bg:green)]($style)'

[git_status]
style = "bg:cyan"
format = '[[($all_status$ahead_behind )](fg:dim_black bg:green)]($style)'

[nodejs]
symbol = ""
style = "bg:cyan"
format = '[[ $symbol( $version) ](fg:dim_black bg:cyan)]($style)'

[c]
symbol = " "
style = "bg:cyan"
format = '[[ $symbol( $version) ](fg:dim_black bg:cyan)]($style)'

[rust]
symbol = ""
style = "bg:cyan"
format = '[[ $symbol( $version) ](fg:dim_black bg:cyan)]($style)'

[golang]
symbol = ""
style = "bg:cyan"
format = '[[ $symbol( $version) ](fg:dim_black bg:cyan)]($style)'

[php]
symbol = ""
style = "bg:cyan"
format = '[[ $symbol( $version) ](fg:dim_black bg:cyan)]($style)'

[java]
symbol = " "
style = "bg:cyan"
format = '[[ $symbol( $version) ](fg:dim_black bg:cyan)]($style)'

[kotlin]
symbol = ""
style = "bg:cyan"
format = '[[ $symbol( $version) ](fg:dim_black bg:cyan)]($style)'

[haskell]
symbol = ""
style = "bg:cyan"
format = '[[ $symbol( $version) ](fg:dim_black bg:cyan)]($style)'

[python]
symbol = ""
style = "bg:cyan"
format = '[[ $symbol( $version) ](fg:dim_black bg:cyan)]($style)'

[docker_context]
symbol = ""
style = "bg:black"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:orange"
format = '[[  $time ](fg:black bg:magenta)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:green)'
error_symbol = '[](bold fg:red)'
vimcmd_symbol = '[](bold fg:green)'
vimcmd_replace_one_symbol = '[](bold fg:magenta)'
vimcmd_replace_symbol = '[](bold fg:magenta)'
vimcmd_visual_symbol = '[](bold fg:bright_magenta)'
